version: "3.9"

services:
  # === Qdrant ===
  qdrant:
    image: qdrant/qdrant:v1.7.3
    container_name: qdrant
    ports:
      - "6333:6333"   # REST gRPC API
      - "6334:6334"   # Optional Web UI
    volumes:
      - qdrant_data:/qdrant/storage

  # === Ollama ===
  ollama:
    build:
      context: ./ollama  # This folder has Dockerfile, entrypoint.sh, Modelfile
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_ORIGINS=*    
      - OLLAMA_HOST=0.0.0.0
    dns:
      - 8.8.8.8
      - 1.1.1.1  

  # === Python App (FastAPI + Streamlit) ===
  rag-app:
    build: .
    container_name: rag-app
    ports:
      - "8000:8000"  # FastAPI
      - "8501:8501"  # Streamlit
    depends_on:
      - qdrant
      - ollama
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - OLLAMA_HOST=ollama
      - OLLAMA_PORT=11434

volumes:
  qdrant_data:
  ollama_data:




# This says:
# “Run three containers → Qdrant, Ollama, and my custom app image (built from the Dockerfile). Wire them together. Open ports.